# fly.toml app configuration file generated for gigachad on 2023-11-24T22:37:07+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gigachad"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
